name: Rust
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Build
        working-directory: rust
        run: cargo build --release --all-features

      - name: Test
        working-directory: rust
        run: cargo test